In [ ]:
import os
import pandas as pd
import kagglehub
from IPython.display import display

# Pobranie danych
path = kagglehub.dataset_download("udaymalviya/bank-loan-data")
print("Path to dataset files:", path)

# Wczytanie pliku
df = pd.read_csv(os.path.join(path, 'loan_data.csv'))

# Zmiana nazwy
df.rename(columns={'loan_amnt': 'loan_amount'}, inplace=True)


a = df[['person_gender', 'person_age', 'person_income']]
b = df.iloc[999:2000]
c = df.iloc[::2]
d = df[df.index % 2 == 0]
e = df.iloc[:, [0, -1]]

display(a, b, c, d, e)

Downloading to /root/.cache/kagglehub/datasets/udaymalviya/bank-loan-data/1.archive...

100%|██████████| 751k/751k [00:00<00:00, 42.7MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/udaymalviya/bank-loan-data/versions/1

      person_gender  person_age  person_income
0            female        22.0        71948.0
1            female        21.0        12282.0
2            female        25.0        12438.0
3            female        23.0        79753.0
4              male        24.0        66135.0
...             ...         ...            ...
44995          male        27.0        47971.0
44996        female        37.0        65800.0
44997          male        33.0        56942.0
44998          male        29.0        33164.0
44999          male        24.0        51609.0

[45000 rows x 3 columns]

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
999,25.0,female,High School,67409.0,4,RENT,18000.0,HOMEIMPROVEMENT,10.99,0.27,4.0,646,No,1
1000,23.0,male,Bachelor,30059.0,0,MORTGAGE,1375.0,MEDICAL,11.11,0.05,4.0,506,No,1
1001,24.0,male,Bachelor,68258.0,2,RENT,18000.0,EDUCATION,13.48,0.26,3.0,671,No,1
1002,21.0,male,Bachelor,60821.0,0,RENT,18000.0,EDUCATION,14.74,0.30,2.0,530,No,1
1003,25.0,male,High School,70432.0,6,RENT,18000.0,VENTURE,11.01,0.26,4.0,609,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,21.0,male,Associate,36953.0,0,MORTGAGE,6400.0,VENTURE,11.01,0.17,3.0,567,Yes,0
1996,21.0,male,Master,37264.0,0,RENT,14000.0,MEDICAL,10.65,0.38,2.0,545,No,1
1997,24.0,female,Associate,36841.0,4,RENT,14000.0,DEBTCONSOLIDATION,7.90,0.38,2.0,538,No,1
1998,24.0,male,Bachelor,37068.0,2,MORTGAGE,3075.0,DEBTCONSOLIDATION,11.01,0.08,4.0,521,Yes,0
1999,22.0,male,Bachelor,37513.0,0,RENT,14000.0,VENTURE,6.99,0.37,4.0,595,No,1

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
6,26.0,female,Bachelor,93471.0,1,RENT,35000.0,EDUCATION,12.42,0.37,3.0,701,No,1
8,24.0,female,Associate,100684.0,3,RENT,35000.0,PERSONAL,8.90,0.35,2.0,544,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44990,31.0,male,Master,136832.0,9,RENT,12319.0,PERSONAL,16.92,0.09,7.0,722,No,1
44992,23.0,female,Bachelor,40925.0,0,RENT,9000.0,PERSONAL,11.01,0.22,4.0,487,No,1
44994,24.0,female,Associate,31924.0,2,RENT,12229.0,MEDICAL,10.70,0.38,4.0,678,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
6,26.0,female,Bachelor,93471.0,1,RENT,35000.0,EDUCATION,12.42,0.37,3.0,701,No,1
8,24.0,female,Associate,100684.0,3,RENT,35000.0,PERSONAL,8.90,0.35,2.0,544,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44990,31.0,male,Master,136832.0,9,RENT,12319.0,PERSONAL,16.92,0.09,7.0,722,No,1
44992,23.0,female,Bachelor,40925.0,0,RENT,9000.0,PERSONAL,11.01,0.22,4.0,487,No,1
44994,24.0,female,Associate,31924.0,2,RENT,12229.0,MEDICAL,10.70,0.38,4.0,678,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1

       person_age  loan_status
0            22.0            1
1            21.0            0
2            25.0            1
3            23.0            1
4            24.0            1
...           ...          ...
44995        27.0            1
44996        37.0            1
44997        33.0            1
44998        29.0            1
44999        24.0            1

[45000 rows x 2 columns]